CREATE DATABASE IF NOT EXISTS WAREHOUSE;
USE WAREHOUSE;
CREATE TABLE IF NOT EXISTS CITIES(
CITY_ID INTEGER NOT NULL PRIMARY KEY ,
  CITY CHAR(20) NOT NULL,
  STATE CHAR(20) NOT NULL);
  ALTER TABLE CITIES ADD CONSTRAINT UNIQUE_CITY_STATE UNIQUE(CITY,STATE);